### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by ajoardar007** [UW-Advanced-Robotics-Lab/lab-documentation#4]
When registering your PC ([Link](https://github.com/UW-Advanced-Robotics-Lab/lab-wiki/wiki/Waterloo-Steel%3APlatform-Setup-Workstation#143-hot_pepper-register-your-pc-in-commonh)), under "Optional (2)", there is the following typo:

Since we want to copy the default debug verbosity configuration under each user's name, instead of 
`cp $UWARL_CONFIGS/scripts/configs/uwarl-rosconsole.config $UWARL_CONFIGS/scripts/configs/uwarl-rosconsole_{user}.config`, wouldn't it be better to write
`ic_copy $UWARL_CONFIGS/scripts/configs/uwarl-rosconsole.config $UWARL_CONFIGS/scripts/configs/uwarl-rosconsole_{$USER}.config` 
in the PC registeration `elif` in `common.sh`?

I also think we should add the line
`# console config:
 export ROSCONSOLE_CONFIG_FILE=$UWARL_CONFIGS/scripts/configs/uwarl-rosconsole_{$USER}.config # debug level`
also in the PC registeration `elif` in `common.sh`. It will get automated, right?

**Comment by jaku-jaku** [comment]
It's not a typo; it is intentional. `$USER` is based on your user on your pc. It does not necessarily mean that you want this ros-console config to be dependent on the pc but rather your own branch. So you do not loose your config crossing platforms. And you have to make the file in the first place, so I specify `{user}` as `{description}` to differentiate. 

Refer to https://github.com/UW-Advanced-Robotics-Lab/uwarl-robot_configs/blob/waterloo_steel/universal/ros1/main/scripts/configs/uwarl-rosconsole_jx.config
